apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ printf "%s-nginx" (include "releasename" .) | quote }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen        80;
        server_name   localhost;
        root          /var/www;
        index         index.php;

        location / {
            try_files $uri $uri/ @proxy;
        }

        # redirect server error pages
        error_page  404              /404.html;
        location = /504.html {
            root   /usr/share/nginx/html;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        location @proxy {
           fastcgi_pass   127.0.0.1:9000;
           fastcgi_index  index.php;
           fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
           include        fastcgi_params;
        }
    }
